<a href="https://colab.research.google.com/github/CODIFICADOR007/CLOUD_PRO/blob/master/colud_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 2**

In [ ]:
#Q1
import random
import time
mytime=time.process_time()
mytime2=time.time()
import numpy as np
dataset=np.random.random((65000,10000))
print(mytime2)
print(dataset)

1662541222.5886893
[[0.97892848 0.00583009 0.94604326 ... 0.79950197 0.61404047 0.82650774]
 [0.38548119 0.44919706 0.70516547 ... 0.25977917 0.45970532 0.730662  ]
 [0.52223696 0.16981325 0.33389085 ... 0.81581413 0.42617834 0.18357348]
 ...
 [0.79368158 0.16900863 0.84827585 ... 0.64955415 0.20191635 0.72014456]
 [0.35255517 0.74540769 0.21848053 ... 0.69192819 0.37917598 0.94387092]
 [0.91121979 0.25821898 0.51408195 ... 0.0478809  0.55987383 0.37643664]]


In [ ]:
#Q2
import time
mytime=time.process_time()
newarr=dataset[0:10001][0:10000]
print(len(newarr))
mydict=dict()

res = {newarr[0][ele] :  newarr[ele + 1] for ele in range(len(newarr) - 1)}
print(res)
print(mytime)

Streaming output truncated to the last 5000 lines.
       0.88168536]), 0.5589152682197686: array([0.50173761, 0.55073207, 0.03965134, ..., 0.17574243, 0.36117765,
       0.45155597]), 0.1827462722387636: array([0.8482637 , 0.68289438, 0.77478404, ..., 0.14395548, 0.53040975,
       0.9431796 ]), 0.19949613207373185: array([0.48402691, 0.82612088, 0.82104627, ..., 0.30309979, 0.99073629,
       0.65774088]), 0.1347922100987582: array([3.82014640e-01, 5.22819842e-02, 9.04685018e-01, ...,
       8.37500860e-04, 3.42740988e-01, 5.81523585e-01]), 0.9823948283177721: array([0.63710225, 0.43595514, 0.9132858 , ..., 0.21478359, 0.11625847,
       0.14812468]), 0.1759924701332466: array([0.2474066 , 0.64845087, 0.0168785 , ..., 0.84354667, 0.91934383,
       0.44543786]), 0.7848394969437468: array([0.27219812, 0.84765394, 0.16542473, ..., 0.93126886, 0.96083147,
       0.11835016]), 0.9915601051736578: array([0.80158766, 0.30733483, 0.35070922, ..., 0.64407144, 0.68308523,
       0.55666172]),

In [ ]:
#Q3
import numpy as np
import pandas as pd
df = pd.DataFrame(dataset)
from itertools import groupby
res = [list(val) for key, val in groupby(sorted(df))]
print(res)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23], [24], [25], [26], [27], [28], [29], [30], [31], [32], [33], [34], [35], [36], [37], [38], [39], [40], [41], [42], [43], [44], [45], [46], [47], [48], [49], [50], [51], [52], [53], [54], [55], [56], [57], [58], [59], [60], [61], [62], [63], [64], [65], [66], [67], [68], [69], [70], [71], [72], [73], [74], [75], [76], [77], [78], [79], [80], [81], [82], [83], [84], [85], [86], [87], [88], [89], [90], [91], [92], [93], [94], [95], [96], [97], [98], [99], [100], [101], [102], [103], [104], [105], [106], [107], [108], [109], [110], [111], [112], [113], [114], [115], [116], [117], [118], [119], [120], [121], [122], [123], [124], [125], [126], [127], [128], [129], [130], [131], [132], [133], [134], [135], [136], [137], [138], [139], [140], [141], [142], [143], [144], [145], [146], [147], [148], [149], [150], [151], [152], [153], [154], [155], [156], [157], [15

In [ ]:
#Q4
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Addition of two matrix")
print(np.add(A, B))
print("Subtraction of two matrix")
print(np.subtract(A, B))

Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [ ]:
#Q5
import itertools
def sub_mat_even(n):
  l=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
  if n%2 == 0:
    for i in range(0,len(l)):
      if i%2 == 1:
        l[i][:] = l[i][::-1]
  for i in range(n):
    for j in range(n):
      print(l[i][j],end=" ")
    print()

n = 4
sub_mat_even(n)

1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [ ]:
#Q6
list1 = [[('My', 1)], [('name', 2)], [('is', 3)], [('VNS', 4)]]
list2= [5, 6, 7, 8]
res = [[(idx, val) for idx in key] for key, val in zip(list1, list2)]
print("The matrix after row elements addition : " + str(res))

The matrix after row elements addition : [[(('My', 1), 5)], [(('name', 2), 6)], [(('is', 3), 7)], [(('VNS', 4), 8)]]


**Assignment 3**

In [ ]:
#Q1
import numpy as np
list_1=np.random.randint(0,50,50)
sum(list_1)

1263

In [ ]:
#Q2
max(list_1)

49

In [ ]:
#Q3
list_of_tuples = [(1,3,4),
                  (9,1,7),
                  (5,8,2)]

sorted(list_of_tuples, key=lambda x: x[-1])

[(5, 8, 2), (1, 3, 4), (9, 1, 7)]

In [ ]:
#Q4
set_1=set(list_1)
list_2=list(set_1)
list_2

[0,
 1,
 2,
 3,
 4,
 6,
 7,
 11,
 12,
 13,
 14,
 16,
 17,
 22,
 24,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 35,
 40,
 41,
 43,
 44,
 45,
 46,
 47,
 49]

In [ ]:
#Q5
names=['lsknd','gnkjvnkwjefgnvjdfvdsn','fnjsadn','ngnefkjnjkasd','vndkjgvjdfdngdsvn']
list_3=[name for name in names if len(name)<8 ]
list_3

['lsknd', 'fnjsadn']

In [ ]:
#Q6
list_4=[7,6,9,10]
list_5=[10,6,5,6]
print(set(list_4)-set(list_5))

{9, 7}


In [ ]:
#Q7
d = {0:10, 1:20}
print(d)
d.update({2:30})
print(d)

{0: 10, 1: 20}
{0: 10, 1: 20, 2: 30}


In [ ]:
#Q8
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic1.update(dic2)
dic1.update(dic3)
print(dic1)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


In [ ]:
#Q9
dic1.pop(1)
print(dic1)

{2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


In [ ]:
#Q10
value=1
for i in dic1.values():
  value=value*i
print(value)

72000000
